# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    name: TEST (${% raw %}{{ matrix.python-version }}{% endraw %}, ${% raw %}{{ matrix.os }}{% endraw %})
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}
          auto-update-conda: true
          environment-file: dev-environment.yml
          activate-environment: {{ cookiecutter.package_name }}-dev

      - name: Checking import order with isort
        shell: bash -l {0}
        run: isort --recursive --diff .

      - name: Checking with flake8
        shell: bash -l {0}
        run: flake8

      - name: Running tests with pytest
        shell: bash -l {0}
        run: pytest --cov --cov-fail-under=20

      # too inconsistent - breaks
      # - name: Checking formatting with black
      #   shell: bash -l {0}
      #   run: black -l 80 --check .
