site_name: {{ cookiecutter.project_name }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash

